### ISSUE TITLE
Reconsider Use of >

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-macros#101]
This issue spans a bit of ZIO Macros and ZIO Core so raising it in both places. I think we should consider moving away from the `>` pattern for accessors for environmental effects and instead just putting accessors in the companion object directly. This is the pattern we use in ZIO Core and ZIO Test and if you look at the Netflix presentation for example it seems to provide a very nice object oriented syntax that people are used to. In contrast especially with the `.` before and after `.>.` can seem quite awkward.

We're already doing this in core so concretely I think this would potentially involve two things:
1. Updating ZIO Macros to generate accessors in the companion object by default. Maybe `@accessible` generates them there by default and then if you give an argument like `>` it generates them in that object.
2. Updating documentation on ZIO site and elsewhere which will already be necessary to some extent with new environment encoding

What do other people think?

**Comment by jdegoes** [comment]
Any takers? 😄

**Comment by ragb** [comment]
What is the status of this? I'd like to help but not sure if it is wise to start before adaptations to RC18 are decided.

**Comment by ioleo** [comment]
@ragb Actually I'm just finishing a PR to `zio/zio` which moves the `@Accessible` macro there and also drops the `>` (instead generates the accessors directly into companion object).

Closeing as done.
