### ISSUE TITLE
Service Macro

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-macros#16]
Imported issue from zio-delegate:

> Is there any chance we could also provide a macro that generates all the Service junk?
   I'd love to just say @zio.service final case class MyConfig(name: String) and automatically get a 
   MyConfig.Service without boilerplate

**Comment by ioleo** [comment]
@NeQuissimus could you elaborate what the expected outcome should be?

**Comment by NeQuissimus** [comment]
I would like have this code:

```scala
@zio.service
final case class Foo(host: String, port: Int)
```

and have the following code generated by the annotation macro:

```scala
trait FooSvc extends Serializable {
 val foo: FooSvc.Service[Any]
}

object FooSvc {
  trait Service[R] extends Serializable {
    def provide: TaskR[R, Foo]
  }
}
```

**Comment by ioleo** [comment]
With `Has` this can be achieved by simply requireing `R <: Has[Foo]`, so this is no longer needed.
