### ISSUE TITLE
Suggested non-operator container for accessors / helpers

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-macros#19]
Right now, helpers are generated into `>` inside the companion object, e.g.:

```scala
@accessable
trait Example {
  val example: Example.Service[Any]
}

object Example {
  trait Service[R] {
    def foo()                 : ZIO[R, Nothing, Unit]
    def bar(v1: Int, v2: Int) : ZIO[R, Nothing, Int]
    def baz(v1: Int)(v2: Int) : ZIO[R, Nothing, String]
  }

  // -- below code is autogenerated -- //
  object > extends Service[R] {
    def foo()                 = ZIO.accessM(_.example.foo)
    def bar(v1: Int, v2: Int) = ZIO.accessM(_.example.bar(v1, v2))
    def baz(v1: Int)(v2: Int) = ZIO.accessM(_.example.baz(v1)(v2))
  }
  // -- end of autogenerated code -- //
}
```

I'd suggest 2 things, first, generate a trait with the helpers, so users have more flexible consumption:

```scala
@accessable
trait Example {
  val example: Example.Service[Any]
}

object Example {
  trait Service[R] {
    def foo()                 : ZIO[R, Nothing, Unit]
    def bar(v1: Int, v2: Int) : ZIO[R, Nothing, Int]
    def baz(v1: Int)(v2: Int) : ZIO[R, Nothing, String]
  }

  // -- below code is autogenerated -- //
  trait Accessors extends Service[R] {
    def foo()                 = ZIO.accessM(_.example.foo)
    def bar(v1: Int, v2: Int) = ZIO.accessM(_.example.bar(v1, v2))
    def baz(v1: Int)(v2: Int) = ZIO.accessM(_.example.baz(v1)(v2))
  }
  // -- end of autogenerated code -- //
}
```

Second, even if `>` remains, I do not think it will be preferred because it has an operator name; so I'd suggest following the ZIO convention to also generate:

```scala
package object example extends Accessors
```

I'm not sure if you can do that, but you could always generate, e.g. `object accessors` inside `Example` companion object, so an import `import Example.accessors._` would bring everything into scope.

**Comment by ioleo** [comment]
I'm leaning towards adding (optional) configuration options.
Something like:
- generate (by default): `trait Accessors` and `object accessors extends Accessors`
- make the object's name configurable so `@accessible(name=">")`

**Comment by neko-kai** [comment]
@ioleo 
> generate (by default): `trait Accessors and object accessors extends Accessors`

This makes sense to me. What also would make sense – if at all possible with macro paradise – is to _not_ autogenerate the object name at all, but instead look for empty objects that extend the service inside the companion object – so you'd declare the name yourself:

```scala
@accessible
trait Example {
  val example: Example.Service[Any]
}

object Example {
  trait Service[R] {
    def foo()                : ZIO[R, Nothing, Unit]
    def bar(v1: Int, v2: Int): ZIO[R, Nothing, Int]
    def baz(v1: Int)(v2: Int): ZIO[R, Nothing, String]
  }
  
  // -- implementation is generated, but not the declaration -- //
  object accessors extends Service[R]
}
```

This has the consequence that auto-import and intellisense will work correctly in the IDE and also users are free to choose the name themselves.

**Comment by ioleo** [comment]
FFR: in case no such object is found, but the module is annotated, the macro should throw compile time error with appropriate message. User should either remove the annotation or add the object.

Another idea to pursue: perhaps the whole file should be searched for matching object. Meaning it would be nice to also support a case where the helper object lies outside of Module companion:

```scala
@accessible
trait Example {
  val example: Example.Service[Any]
}

object Example {
  trait Service[R] {
    def foo()                : ZIO[R, Nothing, Unit]
    def bar(v1: Int, v2: Int): ZIO[R, Nothing, Int]
    def baz(v1: Int)(v2: Int): ZIO[R, Nothing, String]
  }
}
// -- implementation is generated, but not the declaration -- //
object example_ extends Example.Service[Example]
```

**Comment by neko-kai** [comment]
@ioleo 
> Another idea to pursue: perhaps the whole file should be searched for matching object. 

If possible, that would be great. I have no idea of the limits of macro-paradise – you should be able to get the file with `c.internal.enclosingOwner` or `c.enclosingUnit`/`enclosingRun` – but whether you'll be able to override a tree outside of the trait/companion, I wouldn't know.

**Comment by ioleo** [comment]
@neko-kai I've dropped the idea of generating a tree outsite the trait/companion.
If the user needs IDE hints or wants the container anywhere outside, he can simply use `@accessible("trait")` and have only trait generated, which he can extend anywhere.
