### ISSUE TITLE
@accessible does not compile on URIO methods

### ISSUE THREAD

**Issue by pierangeloc** [zio/zio-macros#23]
If I have a method within a module service with `URIO` in the type signature, I get a compilation error 

```scala
@accessible
trait ModuleMacros {
  val moduleMacros: ModuleMacros.Service[Any]
}

object ModuleMacros {
  trait Service[R] {
    def m1: URIO[R, Int]
  }
}
```

The error I get is:
```
object creation impossible, since method m1 in trait Service of type => zio.URIO[io.tuliplogic.raytracer.geometry.affine.ModuleMacros,Int] is not defined
```

However if I replace `URIO` with the unaliased version, as 
```scala
    def m1: ZIO[R, Nothing, Int]
```
the compilation succeeds

**Comment by mschuwalow** [comment]
I'll take a look at this one

**Comment by ioleo** [comment]
Basically the macro at this moment does not handle aliases.
To fix this we need to add all the aliases in `extractCapabilities` https://github.com/zio/zio-macros/blob/master/core/shared/src/main/scala/zio/macros/core/ModulePattern.scala#L136

**Comment by ioleo** [comment]
@mschuwalow do you plan to take on this one? if not I'll have some time later today and could do this

**Comment by mschuwalow** [comment]
> @mschuwalow do you plan to take on this one? if not I'll have some time later today and could do this

Feel free to take it :)
