### ISSUE TITLE
Port Mix macro to dotty

### ISSUE THREAD

**Issue by neko-kai** [zio/zio-macros#56]
The `Mix` macro is portable to dotty since it's an implicit blackbox macro – one of the kind of macros supported in dotty, unlike the macro annotation macros in this library.
The implementor should implement a version of `Mix` macro for dotty, either from scratch or by inspiration from other dotty libraries that use macros, seen below:

There is some documentation for the new macro system, `tasty-reflect`:
- https://dotty.epfl.ch/docs/reference/metaprogramming/tasty-reflect.html
- https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html

There are also example projects with dotty macros:
* Scalatest - https://github.com/dotty-staging/scalatest/blob/dotty-community-build/scalactic.dotty/src/main/scala/org/scalactic/BooleanMacro.scala
* Spire 3 - https://github.com/bishabosha/spire-scala3/blob/master/src/main/scala/spire/syntax/macros/cforMacros.scala
* other library ports for dotty - https://github.com/dotty-staging/

**Comment by mschuwalow** [comment]
Thanks for the links, I'm sure they'll prove very useful.

I plan to both port the macro to dotty as well as clean up the current implementation. I'll probably be quite caught up in zio-{keeper, http} for a while, but as soon as that calms down I'll spend some time here.

**Comment by neko-kai** [comment]
Additional docs:
walkthrough of porting `f""` interpolator to dotty - https://infoscience.epfl.ch/record/267528

**Comment by mschuwalow** [comment]
Thanks for the link! I have started work on this at https://github.com/mschuwalow/zio-macros/tree/delegate-dotty. Currently the biggest blocker for me is finding an equivalent to Type#baseClasses from the current API, but other than that I'm making progress on it.

If you have time we can maybe have a look together in London

**Comment by neko-kai** [comment]
@mschuwalow 
Couldn't find it, it exists in the compiler, but seems like it's not exposed yet. There is `ClassDef_parents` method – maybe using `unseal` and using that on TypeTree could work?
Actually, you could try going `typeOf[X].classSymbol.tree`, comment says it should return ClassDef, which you could probably call `.parents` on:

```
    /** Tree of this definition
     *
     * if this symbol `isPackageDef` it will return a `PackageDef`,
     * if this symbol `isClassDef` it will return a `ClassDef`,
     * if this symbol `isTypeDef` it will return a `TypeDef`,
     * if this symbol `isValDef` it will return a `ValDef`,
     * if this symbol `isDefDef` it will return a `DefDef`
     * if this symbol `isBind` it will return a `Bind`
     */
    def tree(given ctx: Context): Tree =
      internal.Symbol_tree(self)
```

> If you have time we can maybe have a look together in London

Looking forward to it! :+1:

**Comment by ioleo** [comment]
Closing as `@delegate` family got obsoleted by new environment encoding with `Has` and `ZLayer`.
